TARGET_POOLS = [
    {"name": "Schwimmhalle Fischerinsel", "type": "Hallenbad", "detail_url": "https://www.berlinerbaeder.de/baeder/detail/schwimmhalle-fischerinsel/"},
    {"name": "Stadtbad Tiergarten", "type": "Hallenbad", "detail_url": "https://www.berlinerbaeder.de/baeder/detail/stadtbad-tiergarten/"},
    {"name": "Stadtbad Mitte \"James Simon\"", "type": "Hallenbad", "detail_url": "https://www.berlinerbaeder.de/baeder/detail/stadtbad-mitte-james-simon/"},
    {"name": "Schwimm- und Sprunghalle im Europasportpark (SSE)", "type": "Hallenbad", "detail_url": "https://www.berlinerbaeder.de/baeder/detail/schwimm-und-sprunghalle-im-europasportpark-sse/"},
    {"name": "Schwimmhalle Thomas-Mann-Straße", "type": "Hallenbad", "detail_url": "https://www.berlinerbaeder.de/baeder/detail/schwimmhalle-thomas-mann-strasse/"},
    {"name": "Wellenbad am Spreewaldplatz", "type": "Hallenbad", "detail_url": "https://www.berlinerbaeder.de/baeder/detail/wellenbad-am-spreewaldplatz/"},
    {"name": "Stadtbad Schöneberg \"Hans Rosenthal\"", "type": "Hallenbad", "detail_url": "https://www.berlinerbaeder.de/baeder/detail/stadtbad-schoeneberg-hans-rosenthal/"},
    {"name": "Stadtbad Charlottenburg (Alte Halle)", "type": "Hallenbad", "detail_url": "https://www.berlinerbaeder.de/baeder/detail/stadtbad-charlottenburg-alte-halle/"},
    {"name": "Stadtbad Charlottenburg (Neue Halle)", "type": "Hallenbad", "detail_url": "https://www.berlinerbaeder.de/baeder/detail/stadtbad-charlottenburg-neue-halle/"},
    {"name": "Stadtbad Wilmersdorf I", "type": "Hallenbad", "detail_url": "https://www.berlinerbaeder.de/baeder/detail/stadtbad-wilmersdorf-i/"},
    {"name": "Stadtbad Wilmersdorf II", "type": "Hallenbad", "detail_url": "https://www.berlinerbaeder.de/baeder/detail/stadtbad-wilmersdorf-ii/"},
    {"name": "Stadtbad Neukölln", "type": "Hallenbad", "detail_url": "https://www.berlinerbaeder.de/baeder/detail/stadtbad-neukoelln/"},
    {"name": "Schwimmhalle Holzmarktstraße", "type": "Hallenbad", "detail_url": "https://www.berlinerbaeder.de/baeder/detail/schwimmhalle-holzmarktstrasse/"},
    {"name": "Schwimmhalle Anton-Saefkow-Platz", "type": "Hallenbad", "detail_url": "https://www.berlinerbaeder.de/baeder/detail/schwimmhalle-anton-saefkow-platz/"},
    {"name": "Schwimmhalle Ernst-Thälmann-Park", "type": "Hallenbad", "detail_url": "https://www.berlinerbaeder.de/baeder/detail/schwimmhalle-ernst-thaelmann-park/"},
    {"name": "Stadtbad Tempelhof", "type": "Hallenbad", "detail_url": "https://www.berlinerbaeder.de/baeder/detail/stadtbad-tempelhof/"},
    {"name": "Stadtbad Lankwitz", "type": "Hallenbad", "detail_url": "https://www.berlinerbaeder.de/baeder/detail/stadtbad-lankwitz/"},
    {"name": "Kombibad Seestraße - Halle", "type": "Hallenbad", "detail_url": "https://www.berlinerbaeder.de/baeder/detail/kombibad-seestrasse-halle/"},
    {"name": "Kombibad Gropiusstadt - Halle", "type": "Hallenbad", "detail_url": "https://www.berlinerbaeder.de/baeder/detail/kombibad-gropiusstadt-halle/"},
    {"name": "Schwimmhalle Baumschulenweg", "type": "Hallenbad", "detail_url": "https://www.berlinerbaeder.de/baeder/detail/schwimmhalle-baumschulenweg/"},
    {"name": "Sommerbad Kreuzberg", "type": "Sommerbad", "detail_url": "https://www.berlinerbaeder.de/baeder/detail/sommerbad-kreuzberg/"},
    {"name": "Sommerbad Neukölln", "type": "Sommerbad", "detail_url": "https://www.berlinerbaeder.de/baeder/detail/sommerbad-neukoelln/"},
    {"name": "Sommerbad Humboldthain", "type": "Sommerbad", "detail_url": "https://www.berlinerbaeder.de/baeder/detail/sommerbad-humboldthain/"},
    {"name": "Sommerbad Olympiastadion", "type": "Sommerbad", "detail_url": "https://www.berlinerbaeder.de/baeder/detail/sommerbad-olympiastadion/"},
    {"name": "Kinderbad Monbijou", "type": "Sommerbad", "detail_url": "https://www.berlinerbaeder.de/baeder/detail/kinderbad-monbijou/"},
    {"name": "Sommerbad am Insulaner", "type": "Sommerbad", "detail_url": "https://www.berlinerbaeder.de/baeder/detail/sommerbad-am-insulaner/"},
    {"name": "Sommerbad Wilmersdorf", "type": "Sommerbad", "detail_url": "https://www.berlinerbaeder.de/baeder/detail/sommerbad-wilmersdorf/"},
    {"name": "Kombibad Seestraße - Sommerbad", "type": "Sommerbad", "detail_url": "https://www.berlinerbaeder.de/baeder/detail/kombibad-seestrasse-sommerbad/"},
    {"name": "Sommerbad Pankow", "type": "Sommerbad", "detail_url": "https://www.berlinerbaeder.de/baeder/detail/sommerbad-pankow/"},
    {"name": "Sommerbad Mariendorf", "type": "Sommerbad", "detail_url": "https://www.berlinerbaeder.de/baeder/detail/sommerbad-mariendorf/"},
    {"name": "Strandbad Wannsee", "type": "Sommerbad", "detail_url": "https://www.berlinerbaeder.de/baeder/detail/strandbad-wannsee/"},
    {"name": "Schwimmhalle Kreuzberg", "type": "Hallenbad", "detail_url": "https://www.berlinerbaeder.de/baeder/detail/schwimmhalle-kreuzberg/"}
]
